server:
  port: 9006
spring:
  application:
    name: fleet-location-ingest
  cloud:
    stream:
      bindings:
        output: vehicles
eureka.instance.hostname: localhost
eureka.instance.leaseRenewalIntervalInSeconds: 5